apiVersion: v1
kind: Service
metadata:
  name: orders-api
  namespace: k8s-learning
spec:
  selector:
    app: orders-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP   # we'll reach this via `kubectl port-forward` for now;
                     # Ingress comes in Phase 2 of the roadmap
